name: My First CI
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.version.outputs.version }}

    env:
      APP_ENV: production
      APP_NAME: Notes-App
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Get version
        id: version
        run: echo "version=v1.0">> "$GITHUB_OUTPUT"
      - name: show environment
        run: |
          echo "environment: $APP_ENV"
          echo "App- Name: $APP_NAME"
      - name: test secret
        run: |
          if [ -n "${{ secrets.MY_SECRET }}" ]; then
            echo "Secret exists: true"
          else
            echo "Secret exists: false"
          fi
            
      
      - name: test
        run: echo "testing...."

     
      
      - name: Always run step
        if: always()
        run: echo " This step always runs!"
             
      - name: success message
        if: success()
        run: echo "All previous steps are successful!"

      - name: Development check
        if: env.APP_ENV == 'development'
        run: echo "This is development environment"

      - name: production development check
        if: env.APP_ENV == 'production' && success()
        run: echo "production development is allowed!"

      - name: production or staging check
        if: env.APP_ENV == 'production' || env.APP_ENV == 'staging'
        run: echo "production or staging environment detected!"
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Show version
        run: echo "Version is ${{ needs.test.outputs.app-version }}"
      - name: build
        run: echo "building.."
  